timezone: GMT+3

server:
  port: ${vcap.application.port:9099}


oauth:
  checkToken: ${uaaUrl}/check_token
  clientId: ${clientId:timezoneapp}
  clientSecret: ${clientSecret:timezoneappclientsecret}
#spring:
#  jpa:
#    generate-ddl: true


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/

---
#spring:
#  profiles: cloud
#eureka:
#  instance:
#    hostname: ${vcap.application.uris[0]}
#    nonSecurePort: 80